// flow-typed signature: 67578982e5b9cd2dab6a0b5d2d9cb8d8
// flow-typed version: <<STUB>>/eslint-import-resolver-babel-module_v5.1.2/flow_v0.123.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-import-resolver-babel-module'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-import-resolver-babel-module' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-import-resolver-babel-module/lib' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-import-resolver-babel-module/lib/index' {
  declare module.exports: $Exports<'eslint-import-resolver-babel-module/lib'>;
}
declare module 'eslint-import-resolver-babel-module/lib/index.js' {
  declare module.exports: $Exports<'eslint-import-resolver-babel-module/lib'>;
}
